// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzYDuPP-2UCJXzy2SQiNV2XkicbDUi1tM',
    appId: '1:147072395118:android:8ac62bee023ab0fcbbc37f',
    messagingSenderId: '147072395118',
    projectId: 'yoga-app-9d66a',
    databaseURL: 'https://yoga-app-9d66a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yoga-app-9d66a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhThYBLinUawqlJk9L0-08CnR_7E91-Yc',
    appId: '1:147072395118:ios:f67140b95fb9848abbc37f',
    messagingSenderId: '147072395118',
    projectId: 'yoga-app-9d66a',
    databaseURL: 'https://yoga-app-9d66a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yoga-app-9d66a.firebasestorage.app',
    iosBundleId: 'com.example.serenemind',
  );

}